language: python
python:
  - 2.7

install: 
  - 'pip install -r dev_requirements.txt --use-mirrors'

before_script:
  - wget http://googleappengine.googlecode.com/files/google_appengine_1.8.3.zip -nv
  - unzip -q google_appengine_1.8.3.zip
  - export PYTHONPATH=$PYTHONPATH:$PWD/google_appengine

script:
 - ./runtests.sh
